### ISSUE TITLE
Adding Seattle area cameras?

### ISSUE THREAD

**Issue by koogunmo** [wttdotm/traffic_cam_photobooth#1]
Hey there, I love the idea of this project and would love to help add Seattle locations and saw that it was in your TODOs. I did a little digging and found all the Seattle area cameras shown on [this map](https://web.seattle.gov/Travelers/) Some point to City of Seattle DOT cams and some are from Washington DOT maps. I converted them to the format in `allCameras.js` you can see them in [here](https://github.com/user-attachments/files/16592812/converted_traffic_cams.json). I need to clean the data up a bit (like removing highways) but I think it is pretty much all there.

I had a few questions you are cool with me adding Seattle (also happy to fork or let you all handle it)
* I was wondering if 'id' should be a guid right now I'm using the ids given from the SDOT page.
* How did you want to add extra cities? I could just add them to `allCameras.js` but not sure if that made sense or if you wanted to maybe add a drop-down for each city and maybe separate the files?.

**Comment by wttdotm** [comment]
Hey, thanks for offering to contribute! I'm happy to accept PRs for this project, and this is a good time to write out some basic guidelines for doing so.

Here is the basic stuff to keep in mind:

1. Static Site: In general, the site is completely static. It does not have a server, nor do I want to run one. Everything served on the site needs to be already accessible online from a simple GET request. As it stands now, the way images update is just by refreshing the `src` attribute of `<img>` tags. 

2. Camera Data: All cameras should be passed in one big object where they are used. If you see a significant performance drop, you can separate out the `allCameras` object into a separate js file, but the user's device will be responsible for processing that entire list one way or another. This allows the site to find the cameras nearest to the user without their location leaving their device, which is important for user privacy. Every camera needs (at the very least): a name, lat/long coordinates, and an image URL for their feed, following the existing cameras in `allCameras`. Also, camera IDs are passed via URL parameters from one page to another. Keep this pattern.

3. Slowly updating cameras are not a good experience for the user, and I do not want to create a site that encourages people to stand in the street for minutes at a time. With a PR, please provide how often the images (or video) from the cameras will update. Any image refresh rate slower than 15s is probably not worth putting on. (I know this disqualifies many cities, but that's somewhat unavoidable.)

With all that said, go wild!

**Comment by koogunmo** [comment]
Looks like you beat me to it!
