### ISSUE TITLE
Mis-detection of some mobile devices as desktop

### ISSUE THREAD

**Issue by Dan-Q** [wttdotm/traffic_cam_photobooth#5]
## Issue

I'm unable to use this on my Samsung Galaxy S21 Ultra running Firefox Android, because it's mi's-detected as a desktop device.

## Proposed solution

Perhaps free simplest solution might be too add a button to override the detection (eg by applying a CSS class). Eg a "No, this is my mobile" button. This is a solid mitigation to incorrectly gating access as it puts the decision into the hands of the user (who may know the intricacies of their devices better than site authors).

## Screenshot

![Screenshot_20240824_090255_Firefox](https://github.com/user-attachments/assets/3c797116-6971-408c-96f4-4cb1258db802)

**Comment by wttdotm** [comment]
I like a "this is indeed a mobile device button," will add

**Comment by wttdotm** [comment]
This is fixed as of the [most recent commit](https://github.com/wttdotm/traffic_cam_photobooth/commit/cbc5213f6aec80e28b2b0d87c1fd0522fa30de90)
